CREATE TABLE payment_account
(
  ID              UUID,
  PBA_NUMBER      VARCHAR(255) NOT NULL UNIQUE,
  ORGANISATION_ID UUID,
  LAST_UPDATED    TIMESTAMP NOT NULL,
  CREATED         TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORGANISATION_ID) REFERENCES organisation (id)
);

ALTER TABLE professional_user
  ADD COLUMN PAYMENT_ACCOUNT_ID UUID;

ALTER TABLE professional_user
  ADD FOREIGN KEY (PAYMENT_ACCOUNT_ID) REFERENCES payment_account (id);

ALTER TABLE organisation
  ADD COLUMN SRA_ID VARCHAR(255);

ALTER TABLE organisation
  ADD COLUMN SRA_REGULATED BOOLEAN;

ALTER TABLE organisation
  ADD COLUMN COMPANY_NUMBER VARCHAR(255);

ALTER TABLE organisation
  ADD COLUMN COMPANY_URL VARCHAR(512);

ALTER TABLE organisation
  ADD COLUMN ORGANISATION_IDENTIFIER UUID UNIQUE;


